import RPi.GPIO as GPIO
import time

PIN_I2C6_POWER_ENABLE = 17

GPIO.setmode(GPIO.BCM)
GPIO.setup(PIN_I2C6_POWER_ENABLE, GPIO.OUT)
GPIO.output(PIN_I2C6_POWER_ENABLE, GPIO.LOW)
time.sleep(0.1)
GPIO.cleanup()